services:
  server:
    image: nginx:alpine3.20
    container_name: server
    ports:
      - 8080:80
    volumes:
      - ./docker/server/conf/:/etc/nginx/conf.d/
      - ./docker/server/log/:/var/log/nginx/
      - ./app:/var/www
    depends_on:
      - client
      - db
    networks:
      - app_net

  client:
    build: docker/client/
    container_name: client
    ports:
      - 9000:9000
    volumes:
      - ./app:/var/www
    networks:
      - app_net

  db:
    image: postgres:alpine3.20
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - dbstore:/var/lib/postgresql/
      - ./docker/db/log:/var/log/postgresql/
    networks:
      - app_net
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
         
networks:
  app_net:
    name: app_net

volumes:
  dbstore:
    name: ${DATABASE_VOLUME_NAME}
    